[basicInfo]
sendServerHost = "smtp.163.com"
sendServerPort = 25
sendFromUser   = "keryoo@163.com"
senderPasswd   = "sun123456"
sendToUser     = "keryoo@163.com"
carbonCopyUser = "keryoo@163.com"
sendMailTime   = "09:00:00"
